/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package az3eval2assiaamelia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;

/**
 *
 * @author TAOURIRT
 */
public class VueArticle extends javax.swing.JFrame implements Observer{

        
    /**
     * Creates new form VueArticle
     */
    public VueArticle() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnTable = new javax.swing.JPanel();
        jPnTableNord = new javax.swing.JPanel();
        jBPremier = new javax.swing.JButton();
        jBSuivant = new javax.swing.JButton();
        jBPrécedent = new javax.swing.JButton();
        jBDernier = new javax.swing.JButton();
        jPnTableSouth = new javax.swing.JPanel();
        jBNouveau = new javax.swing.JButton();
        jBAjouter = new javax.swing.JButton();
        jBAnnuler = new javax.swing.JButton();
        jBModifier = new javax.swing.JButton();
        jBSupprimer = new javax.swing.JButton();
        jPnTableCentre = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Table Article");

        jPnTable.setLayout(new java.awt.BorderLayout());

        jPnTableNord.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnTableNord.setPreferredSize(new java.awt.Dimension(380, 40));
        jPnTableNord.setLayout(new java.awt.GridLayout(1, 0));

        jBPremier.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBPremier.setText("<<<  Premier");
        jBPremier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPremier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPremier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPremierActionPerformed(evt);
            }
        });
        jPnTableNord.add(jBPremier);

        jBSuivant.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBSuivant.setText("Suivant   >");
        jBSuivant.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBSuivant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBSuivant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSuivantActionPerformed(evt);
            }
        });
        jPnTableNord.add(jBSuivant);

        jBPrécedent.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBPrécedent.setText("<   Précedent");
        jBPrécedent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBPrécedent.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBPrécedent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPrécedentActionPerformed(evt);
            }
        });
        jPnTableNord.add(jBPrécedent);

        jBDernier.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBDernier.setText("Dernier  >>>");
        jBDernier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBDernier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBDernier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDernierActionPerformed(evt);
            }
        });
        jPnTableNord.add(jBDernier);

        jPnTable.add(jPnTableNord, java.awt.BorderLayout.NORTH);

        jPnTableSouth.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPnTableSouth.setPreferredSize(new java.awt.Dimension(405, 40));
        jPnTableSouth.setLayout(new java.awt.GridLayout(1, 0));

        jBNouveau.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBNouveau.setText("Nouveau");
        jBNouveau.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBNouveau.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNouveauActionPerformed(evt);
            }
        });
        jPnTableSouth.add(jBNouveau);

        jBAjouter.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBAjouter.setText("Ajouter");
        jBAjouter.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAjouter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAjouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAjouterActionPerformed(evt);
            }
        });
        jPnTableSouth.add(jBAjouter);

        jBAnnuler.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBAnnuler.setText("Annuler");
        jBAnnuler.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBAnnuler.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPnTableSouth.add(jBAnnuler);

        jBModifier.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBModifier.setText("Modifier");
        jBModifier.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBModifier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModifierActionPerformed(evt);
            }
        });
        jPnTableSouth.add(jBModifier);

        jBSupprimer.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jBSupprimer.setText("Supprimer");
        jBSupprimer.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSupprimerActionPerformed(evt);
            }
        });
        jPnTableSouth.add(jBSupprimer);

        jPnTable.add(jPnTableSouth, java.awt.BorderLayout.SOUTH);

        jPnTableCentre.setBackground(new java.awt.Color(204, 204, 255));
        jPnTableCentre.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPnTableCentre.setForeground(new java.awt.Color(204, 255, 204));
        jPnTableCentre.setPreferredSize(new java.awt.Dimension(405, 200));

        jLabel1.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel1.setText("Code Article");

        jLabel2.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel2.setText("Designation Article ");

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel3.setText("Code Catégorie");

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 0, 14)); // NOI18N
        jLabel4.setText("Prix Unitaire");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 0, 12)); // NOI18N
        jLabel5.setText("Cette application vous permet de parcourir et modifier les enregistrement de la table Article");

        javax.swing.GroupLayout jPnTableCentreLayout = new javax.swing.GroupLayout(jPnTableCentre);
        jPnTableCentre.setLayout(jPnTableCentreLayout);
        jPnTableCentreLayout.setHorizontalGroup(
            jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTableCentreLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(44, 44, 44)
                .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2)
                    .addGroup(jPnTableCentreLayout.createSequentialGroup()
                        .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPnTableCentreLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE))
        );
        jPnTableCentreLayout.setVerticalGroup(
            jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnTableCentreLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPnTableCentreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addContainerGap())
        );

        jPnTable.add(jPnTableCentre, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnTable, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPnTable, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBPremierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPremierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPremierActionPerformed

    private void jBNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNouveauActionPerformed
  
    }//GEN-LAST:event_jBNouveauActionPerformed

    private void jBAjouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAjouterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBAjouterActionPerformed

    private void jBSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSupprimerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSupprimerActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jBSuivantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSuivantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBSuivantActionPerformed

    private void jBPrécedentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPrécedentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBPrécedentActionPerformed

    private void jBDernierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDernierActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDernierActionPerformed

    private void jBModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModifierActionPerformed
   
    }//GEN-LAST:event_jBModifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VueArticle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
      
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jBAjouter;
    public javax.swing.JButton jBAnnuler;
    public javax.swing.JButton jBDernier;
    public javax.swing.JButton jBModifier;
    public javax.swing.JButton jBNouveau;
    public javax.swing.JButton jBPremier;
    public javax.swing.JButton jBPrécedent;
    public javax.swing.JButton jBSuivant;
    public javax.swing.JButton jBSupprimer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public javax.swing.JPanel jPnTable;
    private javax.swing.JPanel jPnTableCentre;
    private javax.swing.JPanel jPnTableNord;
    private javax.swing.JPanel jPnTableSouth;
    public javax.swing.JTextField jTextField1;
    public javax.swing.JTextField jTextField2;
    public javax.swing.JTextField jTextField3;
    public javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
